repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.9"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
